# Numpy giriş

Numpy verileri tek tip şekilde saklar.Bu sayede listelere göre veri anlamaında 4 kat daha az yer kaplar.

## Array

In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [7]:
a * b

array([ 5, 12, 21, 32])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array([3.14,4,2,31])

array([ 3.14,  4.  ,  2.  , 31.  ])

In [10]:
np.array([3.14,4,2,31], dtype='int')

array([ 3,  4,  2, 31])

## Sifirdan array oluşturma

In [12]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### sifirdan olusan matris dondurur.

In [14]:
np.ones((3,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### birden olusan matris dondurur.

In [15]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

##### ilk değer matris satir, ikinci değer matris sutun, ucuncu deger matris icindeki deger olarak matris dondurur.

In [16]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

##### ilk değer baslangic, ikinci değer son deger, ucuncu artis miktari olan matris sonucu dondurur.

In [17]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

##### _linspace_ ilk değer baslangic, ikinci değer son deger, ucuncu deger sayısı olarak sonuc dondurur.

In [19]:
np.random.normal(10, 4, (3,4))

array([[18.10490651, 12.52590496, 13.80830054, 16.88538548],
       [ 8.97048786,  8.54641825,  9.3819229 , 12.04663757],
       [ 9.75698407,  9.17962065,  8.61549541,  2.94780198]])

##### _random.normal_ fonksiyonu ilk **değer ortalama**, ikinci değer **standart sapma**, ucuncu deger matris olarak rastgele sonuc dondurur.

In [21]:
np.random.randint(0, 10, (3,3))

array([[3, 1, 2],
       [7, 5, 5],
       [9, 4, 9]])

##### _random.randint_ fonksiyonu ilk değer baslangic, ikinci değer son deger, ucuncu deger matris olarak rastgele sonuc dondurur.

### Numpy details

In [23]:
x = np.random.randint(10, size = 10)

In [24]:
x.ndim

1

##### _ndim_ komutu bize matrisin boyut sayisini verir

In [25]:
x.shape

(10,)

##### _shape_ komutu bize matrisin boyut bilgisini verir

In [26]:
x.size

10

##### _size_ komutu bize matrisin eleman sayisini verir

In [27]:
a.dtype

dtype('int32')

##### _dtype_ komutu bize matrisin veri tipi bilgisini verir

In [36]:
b = np.random.randint(10, size = (3,5), dtype='int')

In [37]:
b

array([[1, 5, 4, 0, 0],
       [8, 6, 0, 7, 9],
       [6, 1, 2, 4, 2]])

In [38]:
b.ndim

2

In [31]:
b.shape

(3, 5)

In [39]:
b.size

15

In [40]:
b.dtype

dtype('int32')